export enum TipoServicio {
  MONTA_NATURAL = 'MONTA_NATURAL',
  INSEMINACION_ARTIFICIAL = 'INSEMINACION_ARTIFICIAL',
  TRANSFERENCIA_EMBRIONES = 'TRANSFERENCIA_EMBRIONES',
  FERTILIZACION_INVITRO = 'FERTILIZACION_INVITRO',
}

export enum EstadoServicio {
  PROGRAMADO = 'PROGRAMADO',
  REALIZADO = 'REALIZADO',
  FALLIDO = 'FALLIDO',
  CANCELADO = 'CANCELADO',
}
